#= require 'jquery-1-10-2.js'
#= require 'chocolat.js'

$ ->
  $('.choco').Chocolat imageSize: 'contain'
  # $('#example1').Chocolat({
  #     loop           : true,
  #     imageSize     : 'cover',
  #     overlayOpacity : 0.9
  # });
  # $('#example2').Chocolat({
  #     container      : '#container1',
  #     imageSize     : 'contain',
  #     loop           : true,
  # })
  # $('#example3').Chocolat({
  #     container      : '#container2',
  #     imageSize     : 'cover',
  # })

  return

  # ---
  # generated by js2coffee 2.1.0

$(document).ready ->
  $('#toggle').click ->
    $(this).toggleClass 'active'
    $('nav').toggleClass 'mobile-on'
    $('nav').toggleClass 'transition-dismiss'
    $('.logo').toggleClass 'hide'
    $('body').toggleClass 'transition-dismiss'
    $('body, html').toggleClass 'overflow'
    if navigator.userAgent.match('CriOS')
      $('html').toggleClass 'fixed'
    return
  return
$document = $(document)
$document.scroll ->
  if $document.scrollTop() >= 60
    $('header#header').addClass 'notOnTop'
  else
    $('header#header').removeClass 'notOnTop'
  return
lastScrollTop = 0
$(window).scroll (event) ->
  st = $(this).scrollTop()
  if st > lastScrollTop
    $('header#header').removeClass 'scrollup'
  else
    $('header#header').addClass 'scrollup'
    $('header#header').addClass 'opacity'
    $('header#header').removeClass 'scrolldown'
  if st < 1
    $('header#header').removeClass 'scrollup'
    $('header#header').removeClass 'opacity'
  lastScrollTop = st
  return
